[package]
name = "network_spy_proxy"
version = "0.1.0"
edition = "2021"

[lib]
name = "network_spy_proxy"
crate-type = [ "staticlib" ]

[dependencies]
hudsucker = { path = "../hudsucker", features = ["openssl-ca", "rustls-client"] }
async-compression = { version = "0.3.7", features = ["tokio", "brotli", "gzip", "zlib", "zstd"], optional = true }
async-trait = "0.1.7"
bstr = "0.2.1"
bytes = "1.0.0"
futures = "0.3.11"
http = "0.2.0"
hyper = { version = "0.14.7", features = ["client", "http1", "server", "stream", "tcp"] }
hyper-rustls = { version = "0.23.0", default-features = false, features = ["http1", "logging", "tls12", "webpki-tokio"], optional = true }
hyper-tls = { version = "0.5.0", optional = true }
hyper-tungstenite = "0.8.0"
moka = { version = "0.9.0", features = ["future"], optional = true }
openssl = { version = "0.10.25", optional = true }
rand = { version = "0.8.0", optional = true }
rcgen = { version = "0.9.0", features = ["x509-parser"], optional = true }
thiserror = "1.0.23"
time = { version = "0.3.1", optional = true }
tokio = { version = "1.21.0", features = ["full"] }
tokio-rustls = "0.23.0"
tokio-tungstenite = { version = "0.17.2" }
tokio-util = { version = "0.7.0", features = ["io"], optional = true }
tracing = { version = "0.1.21", features = ["log"] }
tracing-subscriber = "0.3.15"
rustls-pemfile = "1.0.1"

[build-dependencies]
cc = "1.0"

[[example]]
name = "openssl"